import { changeOrganizationStatus, createOrganization, getOrganization, listOrganizations, updateOrganization } from '@omniretail/sql-connect';
import { getFirebaseClientServices } from '@/infrastructure/firebase/client';
import { httpsCallable } from 'firebase/functions';
import { DEFAULT_CURRENCY } from '@/shared/utils/currency';
import { Organization, CreateOrganizationInput, UpdateOrganizationInput, OrganizationStatus, OrganizationQuery, PaginatedResult } from '../types';

export interface IOrganizationService { getAllOrganizations(): Promise<Organization[]>; getOrganizations(query: OrganizationQuery): Promise<PaginatedResult<Organization>>; getOrganization(id: string): Promise<Organization | null>; createOrganization(input: CreateOrganizationInput): Promise<Organization>; updateOrganization(id: string, input: UpdateOrganizationInput): Promise<Organization>; changeOrganizationStatus(id: string, status: OrganizationStatus): Promise<Organization>; }
type Row = { id:string; organizationCode:string; businessName:string; legalEntityName?:string|null; taxId?:string|null; primaryContactName:string; email:string; phone:string; address?:string|null; city?:string|null; state?:string|null; postalCode?:string|null; timezone:string; currency:string; status:string; createdAt:string; updatedAt:string };
const uuid = () => globalThis.crypto.randomUUID();
const code = () => `ORG-${uuid().replaceAll('-', '').slice(0, 16).toUpperCase()}`;
function map(row: Row): Organization { return { id: row.id, organizationCode: row.organizationCode, name: row.businessName, legalEntityName: row.legalEntityName ?? '', taxId: row.taxId ?? '', primaryAdmin: row.primaryContactName ? { name: row.primaryContactName, email: row.email, phone: row.phone } : undefined, licensePlan: 'Unassigned', licenseStatus: 'not_assigned', licenseExpiryDate: '—', status: row.status.toLowerCase() as OrganizationStatus, createdDate: row.createdAt.slice(0,10), contactInfo: { primaryContactName: row.primaryContactName, email: row.email, phone: row.phone, address: row.address ?? undefined, city: row.city ?? undefined, state: row.state ?? undefined, pincode: row.postalCode ?? undefined }, timezone: row.timezone, currency: DEFAULT_CURRENCY, allowedStores: undefined, activeStores: undefined, posRegisters: undefined }; }
function safe(error: unknown, fallback: string): Error { const m = error instanceof Error ? error.message : ''; if (/unique|duplicate|already exists/i.test(m)) return new Error('An organization with these details already exists.'); if (/permission|unauthenticated|forbidden/i.test(m)) return new Error('You do not have permission to manage organizations.'); if (/not found/i.test(m)) return new Error('Organization not found.'); return new Error(fallback); }
function validate(input: CreateOrganizationInput|UpdateOrganizationInput) { if (!input.name?.trim()) throw new Error('Business name is required.'); if (!input.primaryContactName?.trim()) throw new Error('Primary contact name is required.'); if (!input.email?.trim()) throw new Error('Email is required.'); if (!input.phone?.trim()) throw new Error('Phone is required.'); if (!/^\+[1-9]\d{7,14}$/.test(input.phone.trim())) throw new Error('Enter a valid international phone number.'); }
export function deriveOrganizationView(all: Organization[], q: OrganizationQuery): PaginatedResult<Organization> {
  let items = [...all];
  const search = q.search?.trim().toLowerCase();
  if (search) items = items.filter((organization) => `${organization.id} ${organization.name} ${organization.contactInfo.primaryContactName} ${organization.contactInfo.city ?? ''}`.toLowerCase().includes(search));
  if (q.organizationStatus && q.organizationStatus !== 'all') items = items.filter((organization) => organization.status === q.organizationStatus);
  if (q.licenseStatus && q.licenseStatus !== 'all') items = items.filter((organization) => organization.licenseStatus === q.licenseStatus);
  const total = items.length;
  const page = Math.max(1, q.page);
  const pageSize = Math.max(1, q.pageSize);
  return { items: items.slice((page - 1) * pageSize, page * pageSize), total, page, pageSize, totalPages: Math.max(1, Math.ceil(total / pageSize)) };
}
class SqlOrganizationService implements IOrganizationService {
  private async rows() { try { const result = await httpsCallable(getFirebaseClientServices().functions, 'listOrganizationsDirectory')({ limit: 1000 }); const rows = (result.data as any).organizations as any[]; return rows.map((r) => ({ ...map(r as Row), licensePlan: r.planName ?? 'Unassigned', licenseExpiryDate: r.licenseExpiryDate ?? '—', licenseStatus: r.licenseStatus ?? 'not_assigned' })); } catch (e) { throw safe(e, 'Unable to load organizations.'); } }
  async getAllOrganizations(): Promise<Organization[]> { return this.rows(); }
  async getOrganizations(q: OrganizationQuery): Promise<PaginatedResult<Organization>> { return deriveOrganizationView(await this.rows(), q); }
  async getOrganization(id:string){ try { const r=await getOrganization(getFirebaseClientServices().dataConnect,{id}); return r.data.organization?map(r.data.organization as Row):null; } catch(e){ throw safe(e,'Unable to load organization.'); } }
  async createOrganization(i:CreateOrganizationInput){ validate(i); try { const id = uuid(); await createOrganization(getFirebaseClientServices().dataConnect,{id,organizationCode:code(),businessName:i.name.trim(),legalEntityName:i.legalEntityName?.trim()||null,taxId:i.taxId?.trim()||null,primaryContactName:i.primaryContactName.trim(),email:i.email.trim().toLowerCase(),phone:i.phone.trim(),address:i.address?.trim()||null,city:i.city?.trim()||null,state:i.state?.trim()||null,postalCode:i.postalCode?.trim()||null,timezone:i.timezone||'Asia/Kolkata (IST)',currency:DEFAULT_CURRENCY}); const created = await this.getOrganization(id); if (!created) throw new Error('not found'); return created; } catch(e){ throw safe(e,'Unable to create organization.'); } }
  async updateOrganization(id:string,i:UpdateOrganizationInput){ validate(i); try { await updateOrganization(getFirebaseClientServices().dataConnect,{id,businessName:i.name.trim(),legalEntityName:i.legalEntityName?.trim()||null,taxId:i.taxId?.trim()||null,primaryContactName:i.primaryContactName.trim(),email:i.email.trim().toLowerCase(),phone:i.phone.trim(),address:i.address?.trim()||null,city:i.city?.trim()||null,state:i.state?.trim()||null,postalCode:i.postalCode?.trim()||null,timezone:i.timezone||'Asia/Kolkata (IST)',currency:DEFAULT_CURRENCY}); const r=await this.getOrganization(id); if(!r)throw new Error('not found'); return { ...r, name: i.name.trim(), contactInfo: { ...r.contactInfo, primaryContactName: i.primaryContactName.trim(), email: i.email.trim().toLowerCase(), phone: i.phone.trim(), address: i.address?.trim() || undefined, city: i.city?.trim() || undefined, state: i.state?.trim() || undefined, pincode: i.postalCode?.trim() || undefined }, primaryAdmin: { name: i.primaryContactName.trim(), email: i.email.trim().toLowerCase(), phone: i.phone.trim() } }; } catch(e){ throw safe(e,'Unable to update organization.'); } }
  async changeOrganizationStatus(id:string,status:OrganizationStatus){ if(status!=='active'&&status!=='suspended')throw new Error('Invalid organization status.'); try { await changeOrganizationStatus(getFirebaseClientServices().dataConnect,{id,status:status.toUpperCase() as never}); const r=await this.getOrganization(id); if(!r)throw new Error('not found'); return { ...r, status }; } catch(e){ throw safe(e,'Unable to change organization status.'); } }
}
export const organizationService: IOrganizationService = new SqlOrganizationService();
