import { Supplier, SupplierCategory, PaymentTerms } from '../types';

export const INITIAL_SUPPLIERS: Supplier[] = [
  // Row 1: Apex Global Electronics (Stitch row 1)
  {
    id: 'sup-101',
    supplierCode: 'SUP-101',
    name: 'Apex Global Electronics',
    contactPerson: 'Marcus Vance',
    phone: '+1 (555) 382-9100',
    email: 'marcus@apexge.com',
    taxId: 'US-8829104',
    address: '104 Madison Ave, Suite 800',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10016',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Net 30 Days',
    creditLimit: 50000,
    status: 'Active',
    notes: 'Primary hardware, thermal receipt printers, and barcode scanners vendor.',
    createdAt: '2023-04-10T09:00:00Z',
    updatedAt: '2024-10-24T14:30:00Z',
    outstandingBalance: 14250.0,
    pendingDeliveriesCount: 3,
    totalOrdersCount: 24,
  },
  // Row 2: Zenith Textile Mills (Stitch row 2)
  {
    id: 'sup-102',
    supplierCode: 'SUP-102',
    name: 'Zenith Textile Mills',
    contactPerson: 'Elena Rostova',
    phone: '+1 (555) 492-1092',
    email: 'orders@zenithtextile.com',
    taxId: 'US-9912041',
    address: '742 Industrial Pkwy',
    city: 'Los Angeles, CA',
    state: 'CA',
    postalCode: '90021',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 15 Days',
    creditLimit: 35000,
    status: 'Active',
    notes: 'Preferred vendor for organic cotton and linen garments.',
    createdAt: '2023-01-15T08:30:00Z',
    updatedAt: '2024-10-22T11:00:00Z',
    outstandingBalance: 8900.0,
    pendingDeliveriesCount: 2,
    totalOrdersCount: 19,
  },
  // Row 3: Cascade Beverage Co. (Stitch row 3)
  {
    id: 'sup-103',
    supplierCode: 'SUP-103',
    name: 'Cascade Beverage Co.',
    contactPerson: 'Derrick Sterling',
    phone: '+1 (555) 781-3321',
    email: 'rep@cascadebev.com',
    taxId: 'US-4401928',
    address: '1800 Harbor Ave SW',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98126',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Cash on Delivery (COD)',
    creditLimit: 20000,
    status: 'Active',
    notes: 'Direct Store Delivery (DSD) beverage partner with weekly cold replenish.',
    createdAt: '2023-06-20T10:15:00Z',
    updatedAt: '2024-10-18T16:45:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 32,
  },
  // Row 4: Horizon Hardware Direct (Stitch row 4)
  {
    id: 'sup-104',
    supplierCode: 'SUP-104',
    name: 'Horizon Hardware Direct',
    contactPerson: 'Sarah Jenkins',
    phone: '+1 (555) 231-9041',
    email: 'wholesale@horizonhw.com',
    taxId: 'US-6610293',
    address: '3200 West Grand Ave',
    city: 'Chicago, IL',
    state: 'IL',
    postalCode: '60651',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 45 Days',
    creditLimit: 45000,
    status: 'Active',
    notes: 'Commercial fixtures, store shelving, and maintenance supplies.',
    createdAt: '2023-03-05T12:00:00Z',
    updatedAt: '2024-10-23T09:20:00Z',
    outstandingBalance: 15300.0,
    pendingDeliveriesCount: 2,
    totalOrdersCount: 14,
  },
  // Row 5: Metro Office Logistics (Stitch row 5 - Inactive)
  {
    id: 'sup-105',
    supplierCode: 'SUP-105',
    name: 'Metro Office Logistics',
    contactPerson: 'Arthur Pendelton',
    phone: '+1 (555) 901-2283',
    email: 'support@metrooffice.org',
    taxId: 'US-1192834',
    address: '890 Biscayne Blvd',
    city: 'Miami, FL',
    state: 'FL',
    postalCode: '33132',
    country: 'United States',
    category: 'Office Supplies',
    paymentTerms: 'Net 30 Days',
    creditLimit: 15000,
    status: 'Inactive',
    notes: 'Replaced by regional bulk distributor. Kept for audit & ledger history.',
    createdAt: '2022-11-12T14:00:00Z',
    updatedAt: '2024-08-30T10:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 11,
  },
  // Row 6: EcoKraft Packaging Ltd.
  {
    id: 'sup-106',
    supplierCode: 'SUP-106',
    name: 'EcoKraft Packaging Ltd.',
    contactPerson: 'Clara Hughes',
    phone: '+1 (555) 612-4490',
    email: 'billing@ecokraft.net',
    taxId: 'US-5510293',
    address: '500 NW 12th Ave',
    city: 'Portland, OR',
    state: 'OR',
    postalCode: '97209',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 25000,
    status: 'Active',
    notes: 'Recyclable shopping bags, bubble mailers, and cardboard cartons.',
    createdAt: '2023-05-18T11:00:00Z',
    updatedAt: '2024-10-15T15:10:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 22,
  },
  // Row 7: Vanguard Leather Goods
  {
    id: 'sup-107',
    supplierCode: 'SUP-107',
    name: 'Vanguard Leather Goods',
    contactPerson: 'Mateo Rossi',
    phone: '+1 (555) 890-3321',
    email: 'orders@vanguardleather.com',
    taxId: 'US-7789012',
    address: '410 Congress Ave',
    city: 'Austin, TX',
    state: 'TX',
    postalCode: '78701',
    country: 'United States',
    category: 'Leather & Accessories',
    paymentTerms: 'Net 15 Days',
    creditLimit: 30000,
    status: 'Active',
    notes: 'Handcrafted wallets, belts, and bespoke retail accessories.',
    createdAt: '2023-08-01T13:40:00Z',
    updatedAt: '2024-10-20T17:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 15,
  },
  // Row 8: Nova Point POS Terminals
  {
    id: 'sup-108',
    supplierCode: 'SUP-108',
    name: 'Nova Point POS Terminals',
    contactPerson: 'Priya Sharma',
    phone: '+1 (555) 441-9982',
    email: 'sales@novapointpos.com',
    taxId: 'US-3321904',
    address: '650 Mission St',
    city: 'San Francisco, CA',
    state: 'CA',
    postalCode: '94105',
    country: 'United States',
    category: 'Point of Sale & Tech',
    paymentTerms: 'Immediate Wire',
    creditLimit: 60000,
    status: 'Active',
    notes: 'EMV chip terminals, customer display hardware, and wireless receipt hubs.',
    createdAt: '2023-09-14T09:15:00Z',
    updatedAt: '2024-10-19T14:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 18,
  },
  // Row 9: Timberline Woodcraft Co.
  {
    id: 'sup-109',
    supplierCode: 'SUP-109',
    name: 'Timberline Woodcraft Co.',
    contactPerson: 'Logan Miller',
    phone: '+1 (555) 312-8871',
    email: 'logan@timberlinewood.com',
    taxId: 'US-4491023',
    address: '1420 16th St Mall',
    city: 'Denver, CO',
    state: 'CO',
    postalCode: '80202',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 30000,
    status: 'Active',
    notes: 'Display pedestals, wooden hangers, and artisanal display units.',
    createdAt: '2023-02-19T10:00:00Z',
    updatedAt: '2024-09-28T11:45:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 9,
  },
  // Row 10: PureSilk Fabric Importers
  {
    id: 'sup-110',
    supplierCode: 'SUP-110',
    name: 'PureSilk Fabric Importers',
    contactPerson: 'Mei-Ling Chen',
    phone: '+1 (555) 678-2341',
    email: 'imports@puresilk.org',
    taxId: 'US-9932014',
    address: '88 Canal St',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10002',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 60 Days',
    creditLimit: 40000,
    status: 'Active',
    notes: 'Premium mulberry silk fabrics, ties, and pocket squares.',
    createdAt: '2023-07-11T15:30:00Z',
    updatedAt: '2024-10-14T09:50:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 13,
  },
  // Row 11: Great Lakes Beverage Depot
  {
    id: 'sup-111',
    supplierCode: 'SUP-111',
    name: 'Great Lakes Beverage Depot',
    contactPerson: 'Liam O’Connor',
    phone: '+1 (555) 762-1140',
    email: 'liam@greatlakesbev.com',
    taxId: 'US-2234019',
    address: '950 E 55th St',
    city: 'Chicago, IL',
    state: 'IL',
    postalCode: '60615',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 15 Days',
    creditLimit: 22000,
    status: 'Active',
    notes: 'Craft sodas, sparkling water pallets, and seasonal juices.',
    createdAt: '2023-05-02T13:00:00Z',
    updatedAt: '2024-10-12T16:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 16,
  },
  // Row 12: Apex Print & Paper Works (Inactive)
  {
    id: 'sup-112',
    supplierCode: 'SUP-112',
    name: 'Apex Print & Paper Works',
    contactPerson: 'David Goldstein',
    phone: '+1 (555) 902-8819',
    email: 'd.goldstein@apexpaper.com',
    taxId: 'US-6671029',
    address: '221 Commercial St',
    city: 'Boston, MA',
    state: 'MA',
    postalCode: '02109',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 18000,
    status: 'Inactive',
    notes: 'Consolidated into EcoKraft supplier agreement.',
    createdAt: '2022-09-15T09:00:00Z',
    updatedAt: '2024-06-30T10:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 8,
  },
  // Row 13: Sunburst Organic Pantry
  {
    id: 'sup-113',
    supplierCode: 'SUP-113',
    name: 'Sunburst Organic Pantry',
    contactPerson: 'Chloe Ramirez',
    phone: '+1 (555) 438-9921',
    email: 'chloe@sunburstpantry.com',
    taxId: 'US-8891024',
    address: '3300 Ocean Dr',
    city: 'Miami, FL',
    state: 'FL',
    postalCode: '33139',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 30 Days',
    creditLimit: 28000,
    status: 'Active',
    notes: 'Organic snacks, trail mixes, and Fair Trade chocolate bars.',
    createdAt: '2023-10-01T11:20:00Z',
    updatedAt: '2024-10-21T13:40:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 20,
  },
  // Row 14: Precision Audio & Mobile
  {
    id: 'sup-114',
    supplierCode: 'SUP-114',
    name: 'Precision Audio & Mobile',
    contactPerson: 'Julian Kim',
    phone: '+1 (555) 551-7890',
    email: 'jkim@precisionaudio.tech',
    taxId: 'US-5541092',
    address: '400 S Hope St',
    city: 'Los Angeles, CA',
    state: 'CA',
    postalCode: '90071',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Net 30 Days',
    creditLimit: 55000,
    status: 'Active',
    notes: 'Retail audio displays, noise cancelling headphones, and charging stations.',
    createdAt: '2023-04-18T14:10:00Z',
    updatedAt: '2024-10-16T11:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 17,
  },
  // Row 15: Nordic Winterwear Ltd.
  {
    id: 'sup-115',
    supplierCode: 'SUP-115',
    name: 'Nordic Winterwear Ltd.',
    contactPerson: 'Astrid Lind',
    phone: '+1 (555) 882-3401',
    email: 'wholesale@nordicwinter.se',
    taxId: 'US-1120938',
    address: '701 Pike St',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98101',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 45 Days',
    creditLimit: 40000,
    status: 'Active',
    notes: 'Thermal coats, merino wool beanies, and weather-resistant parkas.',
    createdAt: '2023-08-25T10:00:00Z',
    updatedAt: '2024-10-24T08:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 12,
  },
  // Row 16: Bay State Retail Fixtures
  {
    id: 'sup-116',
    supplierCode: 'SUP-116',
    name: 'Bay State Retail Fixtures',
    contactPerson: 'Robert Walsh',
    phone: '+1 (555) 234-9912',
    email: 'rwalsh@baystatefixtures.com',
    taxId: 'US-7781023',
    address: '100 High St',
    city: 'Boston, MA',
    state: 'MA',
    postalCode: '02110',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 32000,
    status: 'Active',
    notes: 'Security glass cases, checkout counters, and LED lighting rails.',
    createdAt: '2023-01-28T16:00:00Z',
    updatedAt: '2024-09-19T14:15:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 10,
  },
  // Row 17: Delta Office Supplies
  {
    id: 'sup-117',
    supplierCode: 'SUP-117',
    name: 'Delta Office Supplies',
    contactPerson: 'Monique Taylor',
    phone: '+1 (555) 667-1099',
    email: 'mtaylor@deltaoffice.com',
    taxId: 'US-4439012',
    address: '200 Peachtree St NW',
    city: 'Atlanta, GA',
    state: 'GA',
    postalCode: '30303',
    country: 'United States',
    category: 'Office Supplies',
    paymentTerms: 'Net 30 Days',
    creditLimit: 20000,
    status: 'Active',
    notes: 'Register receipt paper rolls, security tags, and register pens.',
    createdAt: '2023-06-12T10:45:00Z',
    updatedAt: '2024-10-11T12:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 25,
  },
  // Row 18: Pacific Rim Electronics (Inactive)
  {
    id: 'sup-118',
    supplierCode: 'SUP-118',
    name: 'Pacific Rim Electronics',
    contactPerson: 'Kenji Sato',
    phone: '+1 (555) 891-2300',
    email: 'ksato@pacificelec.jp',
    taxId: 'US-9918230',
    address: '505 5th Ave S',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98104',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Net 60 Days',
    creditLimit: 35000,
    status: 'Inactive',
    notes: 'Vendor merged into Apex Global Electronics distribution network.',
    createdAt: '2022-07-10T11:00:00Z',
    updatedAt: '2024-05-15T09:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 6,
  },
  // Row 19: Lone Star Leatherworks
  {
    id: 'sup-119',
    supplierCode: 'SUP-119',
    name: 'Lone Star Leatherworks',
    contactPerson: 'Caleb Morgan',
    phone: '+1 (555) 345-6712',
    email: 'caleb@lonestarleather.com',
    taxId: 'US-6671829',
    address: '1500 Main St',
    city: 'Dallas, TX',
    state: 'TX',
    postalCode: '75201',
    country: 'United States',
    category: 'Leather & Accessories',
    paymentTerms: 'Net 30 Days',
    creditLimit: 28000,
    status: 'Active',
    notes: 'Western boots, belts, leather keychains, and embossed card holders.',
    createdAt: '2023-03-22T13:15:00Z',
    updatedAt: '2024-10-09T15:45:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 14,
  },
  // Row 20: Cascade Thermal Labels
  {
    id: 'sup-120',
    supplierCode: 'SUP-120',
    name: 'Cascade Thermal Labels',
    contactPerson: 'Hannah Brooks',
    phone: '+1 (555) 789-0123',
    email: 'hbrooks@cascadelabels.com',
    taxId: 'US-3391028',
    address: '1201 3rd Ave',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98101',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 15 Days',
    creditLimit: 15000,
    status: 'Active',
    notes: 'Barcode shelf talkers, thermal transfer ribbon, and direct thermal rolls.',
    createdAt: '2023-07-04T09:30:00Z',
    updatedAt: '2024-10-17T11:15:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 21,
  },
  // Row 21: Gotham Specialty Groceries
  {
    id: 'sup-121',
    supplierCode: 'SUP-121',
    name: 'Gotham Specialty Groceries',
    contactPerson: 'Vincenzo Bianchi',
    phone: '+1 (555) 912-3456',
    email: 'vincenzo@gothamgrocer.com',
    taxId: 'US-5519203',
    address: '420 West Broadway',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10012',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 30 Days',
    creditLimit: 25000,
    status: 'Active',
    notes: 'Artisan pasta, aged balsamic vinegar, and olive oils.',
    createdAt: '2023-04-05T10:00:00Z',
    updatedAt: '2024-10-13T14:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 19,
  },
  // Row 22: Pioneer Tool & Fastener
  {
    id: 'sup-122',
    supplierCode: 'SUP-122',
    name: 'Pioneer Tool & Fastener',
    contactPerson: 'Brett Henderson',
    phone: '+1 (555) 234-5678',
    email: 'brett@pioneertool.com',
    taxId: 'US-8819204',
    address: '2200 N Interstate 35',
    city: 'Austin, TX',
    state: 'TX',
    postalCode: '78705',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 30000,
    status: 'Active',
    notes: 'Stockroom utility cutters, staple guns, and ladder equipment.',
    createdAt: '2023-05-20T12:00:00Z',
    updatedAt: '2024-10-08T09:10:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 11,
  },
  // Row 23: Blue Ridge Denim Mill
  {
    id: 'sup-123',
    supplierCode: 'SUP-123',
    name: 'Blue Ridge Denim Mill',
    contactPerson: 'Savannah Cole',
    phone: '+1 (555) 876-5432',
    email: 'scole@blueridgedenim.com',
    taxId: 'US-7729103',
    address: '500 E Main St',
    city: 'Charlotte, NC',
    state: 'NC',
    postalCode: '28202',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 45 Days',
    creditLimit: 40000,
    status: 'Active',
    notes: 'Raw selvedge denim jeans, jackets, and canvas work shirts.',
    createdAt: '2023-02-14T15:00:00Z',
    updatedAt: '2024-10-18T10:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 16,
  },
  // Row 24: Metro Carton & Box Works (Inactive)
  {
    id: 'sup-124',
    supplierCode: 'SUP-124',
    name: 'Metro Carton & Box Works',
    contactPerson: 'Howard Vance',
    phone: '+1 (555) 432-1098',
    email: 'hvance@metrocarton.com',
    taxId: 'US-3310928',
    address: '1801 S Canal St',
    city: 'Chicago, IL',
    state: 'IL',
    postalCode: '60616',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 20000,
    status: 'Inactive',
    notes: 'Facility closed operations in early 2024.',
    createdAt: '2022-05-11T09:00:00Z',
    updatedAt: '2024-03-31T17:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 7,
  },
  // Row 25: Silverline Tech Solutions
  {
    id: 'sup-125',
    supplierCode: 'SUP-125',
    name: 'Silverline Tech Solutions',
    contactPerson: 'Derek Zhao',
    phone: '+1 (555) 765-4321',
    email: 'dzhao@silverlinetech.io',
    taxId: 'US-9910234',
    address: '100 Montgomery St',
    city: 'San Francisco, CA',
    state: 'CA',
    postalCode: '94104',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Net 30 Days',
    creditLimit: 50000,
    status: 'Active',
    notes: 'RFID scanners, anti-theft gates, and NFC card readers.',
    createdAt: '2023-06-28T14:30:00Z',
    updatedAt: '2024-10-15T16:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 15,
  },
  // Row 26: Heartland Grain & Milling
  {
    id: 'sup-126',
    supplierCode: 'SUP-126',
    name: 'Heartland Grain & Milling',
    contactPerson: 'Rachel Adams',
    phone: '+1 (555) 321-0987',
    email: 'radams@heartlandgrain.com',
    taxId: 'US-5549012',
    address: '800 Nicollet Mall',
    city: 'Minneapolis, MN',
    state: 'MN',
    postalCode: '55402',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 15 Days',
    creditLimit: 25000,
    status: 'Active',
    notes: 'Artisan flours, oats, granola mixes, and bakery supplies.',
    createdAt: '2023-01-19T11:00:00Z',
    updatedAt: '2024-09-29T13:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 18,
  },
  // Row 27: Sierra Outdoor Outfitters
  {
    id: 'sup-127',
    supplierCode: 'SUP-127',
    name: 'Sierra Outdoor Outfitters',
    contactPerson: 'Travis Baker',
    phone: '+1 (555) 654-3210',
    email: 'travis@sierraoutfit.com',
    taxId: 'US-2291034',
    address: '1200 S Virginia St',
    city: 'Reno, NV',
    state: 'NV',
    postalCode: '89502',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 30 Days',
    creditLimit: 38000,
    status: 'Active',
    notes: 'Hiking socks, waterproof shells, and UV-resistant outdoor gear.',
    createdAt: '2023-08-14T09:45:00Z',
    updatedAt: '2024-10-19T15:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 14,
  },
  // Row 28: Alamo Display & Glass (Inactive)
  {
    id: 'sup-128',
    supplierCode: 'SUP-128',
    name: 'Alamo Display & Glass',
    contactPerson: 'Ignacio Ortiz',
    phone: '+1 (555) 987-6543',
    email: 'iortiz@alamoglass.com',
    taxId: 'US-8871029',
    address: '300 Convent St',
    city: 'San Antonio, TX',
    state: 'TX',
    postalCode: '78205',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 20000,
    status: 'Inactive',
    notes: 'Vendor contract expired; store displays transitioned to Bay State.',
    createdAt: '2022-10-05T10:30:00Z',
    updatedAt: '2024-04-12T11:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 5,
  },
  // Row 29: Golden Gate Coffee Roasters
  {
    id: 'sup-129',
    supplierCode: 'SUP-129',
    name: 'Golden Gate Coffee Roasters',
    contactPerson: 'Lucia Santos',
    phone: '+1 (555) 210-9876',
    email: 'lucia@ggcoffeeroasters.com',
    taxId: 'US-6619023',
    address: '250 4th St',
    city: 'San Francisco, CA',
    state: 'CA',
    postalCode: '94103',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 15 Days',
    creditLimit: 22000,
    status: 'Active',
    notes: 'Single origin espresso beans, cold brew kegs, and barista oat milk.',
    createdAt: '2023-09-02T13:00:00Z',
    updatedAt: '2024-10-23T16:15:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 26,
  },
  // Row 30: Atlantic Ribbon & Wrap
  {
    id: 'sup-130',
    supplierCode: 'SUP-130',
    name: 'Atlantic Ribbon & Wrap',
    contactPerson: 'Bethany Price',
    phone: '+1 (555) 543-2109',
    email: 'bprice@atlanticwrap.com',
    taxId: 'US-4410923',
    address: '1500 Market St',
    city: 'Philadelphia, PA',
    state: 'PA',
    postalCode: '19102',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 18000,
    status: 'Active',
    notes: 'Gift wrapping paper, satin ribbons, gift tags, and tissue lining.',
    createdAt: '2023-03-10T15:20:00Z',
    updatedAt: '2024-10-10T12:40:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 13,
  },
  // Row 31: Summit Mountain Knits
  {
    id: 'sup-131',
    supplierCode: 'SUP-131',
    name: 'Summit Mountain Knits',
    contactPerson: 'Jonas Weber',
    phone: '+1 (555) 876-0124',
    email: 'jweber@summitknits.com',
    taxId: 'US-1192043',
    address: '350 S Main St',
    city: 'Salt Lake City, UT',
    state: 'UT',
    postalCode: '84101',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 30 Days',
    creditLimit: 32000,
    status: 'Active',
    notes: 'Hand-knitted cardigans, wool scarves, and winter mitts.',
    createdAt: '2023-05-15T11:45:00Z',
    updatedAt: '2024-10-21T09:15:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 15,
  },
  // Row 32: Magnolia Southern Botanicals
  {
    id: 'sup-132',
    supplierCode: 'SUP-132',
    name: 'Magnolia Southern Botanicals',
    contactPerson: 'Camille Dubois',
    phone: '+1 (555) 321-6540',
    email: 'camille@magnoliabotanicals.com',
    taxId: 'US-7749102',
    address: '701 Poydras St',
    city: 'New Orleans, LA',
    state: 'LA',
    postalCode: '70139',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 15 Days',
    creditLimit: 20000,
    status: 'Active',
    notes: 'Botanical iced teas, herbal tonics, and cane sugar syrups.',
    createdAt: '2023-07-20T10:10:00Z',
    updatedAt: '2024-10-14T15:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 17,
  },
  // Row 33: Keystone POS Peripherals
  {
    id: 'sup-133',
    supplierCode: 'SUP-133',
    name: 'Keystone POS Peripherals',
    contactPerson: 'Nathaniel Reed',
    phone: '+1 (555) 654-9870',
    email: 'nreed@keystoneperipherals.com',
    taxId: 'US-3381920',
    address: '600 Grant St',
    city: 'Pittsburgh, PA',
    state: 'PA',
    postalCode: '15219',
    country: 'United States',
    category: 'Point of Sale & Tech',
    paymentTerms: 'Net 30 Days',
    creditLimit: 40000,
    status: 'Active',
    notes: 'Cash drawers, receipt pole mounts, and tablet enclosures.',
    createdAt: '2023-04-12T14:00:00Z',
    updatedAt: '2024-10-16T17:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 20,
  },
  // Row 34: Empire City Stationery (Inactive)
  {
    id: 'sup-134',
    supplierCode: 'SUP-134',
    name: 'Empire City Stationery',
    contactPerson: 'Gloria Stein',
    phone: '+1 (555) 987-1234',
    email: 'gloria@empirestationery.com',
    taxId: 'US-9920194',
    address: '350 5th Ave',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10118',
    country: 'United States',
    category: 'Office Supplies',
    paymentTerms: 'Net 30 Days',
    creditLimit: 15000,
    status: 'Inactive',
    notes: 'Transitioned all stationery procurement to EcoKraft.',
    createdAt: '2022-08-19T08:00:00Z',
    updatedAt: '2024-02-28T16:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 9,
  },
  // Row 35: Cascade Alpine Outerwear
  {
    id: 'sup-135',
    supplierCode: 'SUP-135',
    name: 'Cascade Alpine Outerwear',
    contactPerson: 'Erik Thorson',
    phone: '+1 (555) 432-8765',
    email: 'erik@cascadealpine.com',
    taxId: 'US-5591028',
    address: '1000 2nd Ave',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98104',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 45 Days',
    creditLimit: 45000,
    status: 'Active',
    notes: 'Gore-Tex raincoats, fleece pullovers, and technical climbing apparel.',
    createdAt: '2023-08-30T10:20:00Z',
    updatedAt: '2024-10-22T13:10:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 14,
  },
  // Row 36: Silicon Valley Hardware Labs
  {
    id: 'sup-136',
    supplierCode: 'SUP-136',
    name: 'Silicon Valley Hardware Labs',
    contactPerson: 'Anita Patel',
    phone: '+1 (555) 765-1234',
    email: 'apatel@svhardwarelabs.com',
    taxId: 'US-2210934',
    address: '200 S 1st St',
    city: 'San Jose, CA',
    state: 'CA',
    postalCode: '95113',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Immediate Wire',
    creditLimit: 65000,
    status: 'Active',
    notes: 'Smart shelf weight sensors and Bluetooth beacon tracking units.',
    createdAt: '2023-06-05T13:40:00Z',
    updatedAt: '2024-10-18T15:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 12,
  },
  // Row 37: Desert Sun Leatherworks
  {
    id: 'sup-137',
    supplierCode: 'SUP-137',
    name: 'Desert Sun Leatherworks',
    contactPerson: 'Raul Calderon',
    phone: '+1 (555) 098-7654',
    email: 'rcalderon@desertsunleather.com',
    taxId: 'US-8839012',
    address: '1 E Washington St',
    city: 'Phoenix, AZ',
    state: 'AZ',
    postalCode: '85004',
    country: 'United States',
    category: 'Leather & Accessories',
    paymentTerms: 'Net 30 Days',
    creditLimit: 25000,
    status: 'Active',
    notes: 'Braided leather lanyards, saddle leather bags, and key fobs.',
    createdAt: '2023-02-18T09:30:00Z',
    updatedAt: '2024-09-30T11:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 16,
  },
  // Row 38: Midwest Safety & Security
  {
    id: 'sup-138',
    supplierCode: 'SUP-138',
    name: 'Midwest Safety & Security',
    contactPerson: 'Warren Schmidt',
    phone: '+1 (555) 321-4567',
    email: 'wschmidt@midwestsafety.com',
    taxId: 'US-6649102',
    address: '100 E Wisconsin Ave',
    city: 'Milwaukee, WI',
    state: 'WI',
    postalCode: '53202',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 28000,
    status: 'Active',
    notes: 'Store security mirrors, fire extinguishers, and first aid kits.',
    createdAt: '2023-03-15T16:00:00Z',
    updatedAt: '2024-10-07T14:40:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 10,
  },
  // Row 39: Rainier Natural Spring Water
  {
    id: 'sup-139',
    supplierCode: 'SUP-139',
    name: 'Rainier Natural Spring Water',
    contactPerson: 'Brooke Hansen',
    phone: '+1 (555) 654-7890',
    email: 'bhansen@rainierspring.com',
    taxId: 'US-4420914',
    address: '400 Capitol Way S',
    city: 'Olympia, WA',
    state: 'WA',
    postalCode: '98501',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Cash on Delivery (COD)',
    creditLimit: 15000,
    status: 'Active',
    notes: '5-gallon spring water carboys and eco-glass bottled water.',
    createdAt: '2023-05-25T11:00:00Z',
    updatedAt: '2024-10-19T10:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 22,
  },
  // Row 40: Gotham Carton Co.
  {
    id: 'sup-140',
    supplierCode: 'SUP-140',
    name: 'Gotham Carton Co.',
    contactPerson: 'Samira Khan',
    phone: '+1 (555) 987-3456',
    email: 'skhan@gothamcarton.com',
    taxId: 'US-1182049',
    address: '285 Fulton St',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10007',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 24000,
    status: 'Active',
    notes: 'Custom branded corrugated boxes and packaging tape.',
    createdAt: '2023-04-20T15:10:00Z',
    updatedAt: '2024-10-16T12:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 18,
  },
  // Row 41: Austin Creative Apparel
  {
    id: 'sup-141',
    supplierCode: 'SUP-141',
    name: 'Austin Creative Apparel',
    contactPerson: 'Wyatt Turner',
    phone: '+1 (555) 234-8901',
    email: 'wturner@austincreative.com',
    taxId: 'US-7739104',
    address: '1100 S Congress Ave',
    city: 'Austin, TX',
    state: 'TX',
    postalCode: '78704',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 15 Days',
    creditLimit: 25000,
    status: 'Active',
    notes: 'Custom graphic screen-printed tees and embroidered tote bags.',
    createdAt: '2023-08-11T12:30:00Z',
    updatedAt: '2024-10-21T16:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 15,
  },
  // Row 42: Chicago Industrial Storage
  {
    id: 'sup-142',
    supplierCode: 'SUP-142',
    name: 'Chicago Industrial Storage',
    contactPerson: 'Gordon Vance',
    phone: '+1 (555) 567-2345',
    email: 'gvance@chicagostorage.com',
    taxId: 'US-3319024',
    address: '233 S Wacker Dr',
    city: 'Chicago, IL',
    state: 'IL',
    postalCode: '60606',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 35000,
    status: 'Active',
    notes: 'Heavy-duty steel pallet racks and rolling stockroom ladders.',
    createdAt: '2023-01-30T10:00:00Z',
    updatedAt: '2024-09-25T14:15:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 13,
  },
  // Row 43: Sunshine Citrus Grove Direct
  {
    id: 'sup-143',
    supplierCode: 'SUP-143',
    name: 'Sunshine Citrus Grove Direct',
    contactPerson: 'Maria Morales',
    phone: '+1 (555) 890-5678',
    email: 'mmorales@sunshinecitrus.com',
    taxId: 'US-9941023',
    address: '100 SE 2nd St',
    city: 'Miami, FL',
    state: 'FL',
    postalCode: '33131',
    country: 'United States',
    category: 'Beverages & Groceries',
    paymentTerms: 'Net 15 Days',
    creditLimit: 18000,
    status: 'Active',
    notes: 'Freshly squeezed Florida Valencia orange and ruby grapefruit juice.',
    createdAt: '2023-06-18T14:00:00Z',
    updatedAt: '2024-10-23T11:45:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 20,
  },
  // Row 44: Pacific Thermal Rolls
  {
    id: 'sup-144',
    supplierCode: 'SUP-144',
    name: 'Pacific Thermal Rolls',
    contactPerson: 'Curtis Vance',
    phone: '+1 (555) 123-6789',
    email: 'cvance@pacificthermal.com',
    taxId: 'US-5529104',
    address: '1111 3rd Ave',
    city: 'Seattle, WA',
    state: 'WA',
    postalCode: '98101',
    country: 'United States',
    category: 'Office Supplies',
    paymentTerms: 'Net 30 Days',
    creditLimit: 16000,
    status: 'Active',
    notes: 'BPA-free receipt printer paper and credit card terminal rolls.',
    createdAt: '2023-03-08T09:15:00Z',
    updatedAt: '2024-10-15T13:20:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 19,
  },
  // Row 45: Los Angeles Garment Group
  {
    id: 'sup-145',
    supplierCode: 'SUP-145',
    name: 'Los Angeles Garment Group',
    contactPerson: 'Teresa Navarro',
    phone: '+1 (555) 456-9012',
    email: 'tnavarro@lagarmentgroup.com',
    taxId: 'US-8812093',
    address: '110 E 9th St',
    city: 'Los Angeles, CA',
    state: 'CA',
    postalCode: '90079',
    country: 'United States',
    category: 'Apparel & Textiles',
    paymentTerms: 'Net 30 Days',
    creditLimit: 40000,
    status: 'Active',
    notes: 'Fast-turnaround cotton basics, athletic sweatshirts, and hoodies.',
    createdAt: '2023-07-29T10:40:00Z',
    updatedAt: '2024-10-20T15:30:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 17,
  },
  // Row 46: Boston Marine Hardware
  {
    id: 'sup-146',
    supplierCode: 'SUP-146',
    name: 'Boston Marine Hardware',
    contactPerson: 'Liam Sullivan',
    phone: '+1 (555) 789-2345',
    email: 'lsullivan@bostonmarinehw.com',
    taxId: 'US-6639104',
    address: '60 State St',
    city: 'Boston, MA',
    state: 'MA',
    postalCode: '02109',
    country: 'United States',
    category: 'Tools & Hardware',
    paymentTerms: 'Net 30 Days',
    creditLimit: 30000,
    status: 'Active',
    notes: 'Corrosion-resistant stainless fasteners, rigging, and utility ropes.',
    createdAt: '2023-02-10T13:00:00Z',
    updatedAt: '2024-09-14T11:00:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 12,
  },
  // Row 47: Metro Quick Ship Cartons
  {
    id: 'sup-147',
    supplierCode: 'SUP-147',
    name: 'Metro Quick Ship Cartons',
    contactPerson: 'Damon Clarke',
    phone: '+1 (555) 012-5678',
    email: 'dclarke@metroquickship.com',
    taxId: 'US-4481029',
    address: '400 S Orange Ave',
    city: 'Orlando, FL',
    state: 'FL',
    postalCode: '32801',
    country: 'United States',
    category: 'Packaging & Shipping',
    paymentTerms: 'Net 30 Days',
    creditLimit: 22000,
    status: 'Active',
    notes: 'Same-day corrugated box dispatch for store inventory transfers.',
    createdAt: '2023-05-14T11:30:00Z',
    updatedAt: '2024-10-17T16:45:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 16,
  },
  // Row 48: Gotham Audio Imports
  {
    id: 'sup-148',
    supplierCode: 'SUP-148',
    name: 'Gotham Audio Imports',
    contactPerson: 'Zachary Klein',
    phone: '+1 (555) 345-8901',
    email: 'zklein@gothamaudio.com',
    taxId: 'US-2290134',
    address: '1 World Trade Center',
    city: 'New York, NY',
    state: 'NY',
    postalCode: '10007',
    country: 'United States',
    category: 'Consumer Electronics',
    paymentTerms: 'Net 30 Days',
    creditLimit: 48000,
    status: 'Active',
    notes: 'In-store wireless PA speakers, mic systems, and background music hardware.',
    createdAt: '2023-04-01T15:00:00Z',
    updatedAt: '2024-10-24T12:10:00Z',
    outstandingBalance: 0.0,
    pendingDeliveriesCount: 0,
    totalOrdersCount: 14,
  },
];
