import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1024',
    productCode: 'PRD-1024',
    name: 'Classic Linen Relaxed Shirt',
    brand: 'Punarva Studio',
    categoryId: 'apparel',
    categoryName: 'Apparel / Shirts',
    subcategory: 'Tops / Shirts',
    type: 'stockable',
    sku: 'AP-SH-001',
    barcode: '8904512301',
    hsnCode: '6205.20.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 48.0,
    mrp: 55.0,
    cost: 22.5,
    minSellingPrice: 42.0,
    discountAllowed: true,
    taxCategory: 'GST 12% (Standard Apparel)',
    status: 'active',
    reorderLevel: 30,
    reorderQuantity: 50,
    openingStock: 140,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Zenith Textile Mills (SUP-102)',
    supplierProductCode: 'ZTM-LIN-09',
    description:
      'Breathable pure organic European flax linen shirt featuring coconut shell buttons, relaxed cuban collar, and French reinforced seams.',
    imageUrl:
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Sage green organic European flax linen shirt',
    variantsConfigured: 'Size (S, M, L, XL), Color (Sage, Navy, White)',
    stockSummary: {
      onHandTotal: 142,
      reorderLevel: 30,
      status: 'IN_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Aisle 3 • Rack B-12',
          quantity: 64,
          minThreshold: 15,
          statusText: 'Safe (Min: 15)',
        },
        {
          storeId: 'store-02',
          storeName: 'Northside Galleria #02',
          locationText: 'Aisle 1 • Rack A-04',
          quantity: 42,
          minThreshold: 10,
          statusText: 'Safe (Min: 10)',
        },
        {
          storeId: 'store-03',
          storeName: 'Dallas Uptown #03',
          locationText: 'Backroom Bin 108',
          quantity: 26,
          minThreshold: 10,
          statusText: 'Safe (Min: 10)',
        },
        {
          storeId: 'store-04',
          storeName: 'Houston Galleria #04',
          locationText: 'Floor Display Area',
          quantity: 10,
          minThreshold: 10,
          statusText: 'At Min Threshold (10)',
          isWarning: true,
        },
      ],
    },
    recentActivity: [
      {
        id: 'act-1',
        title: 'Stock Replenishment (+40 units)',
        reference: 'PO-2024-889',
        timeAgo: 'Yesterday',
        type: 'replenishment',
        units: 40,
      },
      {
        id: 'act-2',
        title: 'POS Register Sale (2 units)',
        reference: '#ORD-9843',
        timeAgo: '2 hrs ago',
        type: 'sale',
        units: -2,
      },
    ],
    createdAt: '2024-01-15T08:30:00Z',
    updatedAt: '2024-03-10T14:20:00Z',
  },
  {
    id: 'prod-1025',
    productCode: 'PRD-1025',
    name: 'Structured Canvas Tote Bag',
    brand: 'Zenith Lifestyle',
    categoryId: 'accessories',
    categoryName: 'Accessories / Bags',
    subcategory: 'Bags & Carriers',
    type: 'stockable',
    sku: 'AC-TB-104',
    barcode: '8904512302',
    hsnCode: '4202.92.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 24.0,
    mrp: 30.0,
    cost: 11.0,
    minSellingPrice: 20.0,
    discountAllowed: true,
    taxCategory: 'GST 18% (Luxury Accessories)',
    status: 'active',
    reorderLevel: 25,
    reorderQuantity: 40,
    openingStock: 90,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'EcoKraft Packaging (SUP-105)',
    supplierProductCode: 'EKP-TOT-44',
    description:
      'Heavyweight 16oz cotton canvas tote bag with reinforced dual webbing handles, antique brass snap closures, and interior organizer pocket.',
    imageUrl:
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Structured heavyweight canvas tote bag',
    variantsConfigured: 'Color (Natural Raw, Charcoal, Olive)',
    stockSummary: {
      onHandTotal: 88,
      reorderLevel: 25,
      status: 'IN_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Showcase Rack 02',
          quantity: 48,
          minThreshold: 12,
          statusText: 'Safe (Min: 12)',
        },
        {
          storeId: 'store-04',
          storeName: 'Houston Galleria #04',
          locationText: 'Accessories Island',
          quantity: 40,
          minThreshold: 10,
          statusText: 'Safe (Min: 10)',
        },
      ],
    },
    recentActivity: [
      {
        id: 'act-3',
        title: 'POS Register Sale (1 unit)',
        reference: '#ORD-9839',
        timeAgo: '4 hrs ago',
        type: 'sale',
        units: -1,
      },
    ],
    createdAt: '2024-01-18T10:15:00Z',
    updatedAt: '2024-03-09T11:45:00Z',
  },
  {
    id: 'prod-1026',
    productCode: 'PRD-1026',
    name: 'Tailored Wool Blazer',
    brand: 'Punarva Studio',
    categoryId: 'apparel',
    categoryName: 'Apparel / Outerwear',
    subcategory: 'Jackets & Blazers',
    type: 'stockable',
    sku: 'AP-BL-202',
    barcode: '8904512303',
    hsnCode: '6203.31.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 145.0,
    mrp: 160.0,
    cost: 68.0,
    minSellingPrice: 130.0,
    discountAllowed: false,
    taxCategory: 'GST 12% (Standard Apparel)',
    status: 'active',
    reorderLevel: 25,
    reorderQuantity: 30,
    openingStock: 30,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Zenith Textile Mills (SUP-102)',
    supplierProductCode: 'ZTM-BLZ-88',
    description:
      'Structured single-breasted wool-blend blazer featuring notched lapels, horn buttons, cupro lining, and functional ticket pockets.',
    imageUrl:
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Charcoal tailored wool blazer',
    variantsConfigured: 'Size (38R, 40R, 42R, 44R), Color (Charcoal, Navy)',
    stockSummary: {
      onHandTotal: 22,
      reorderLevel: 25,
      status: 'LOW_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Aisle 2 • Suiting Rack',
          quantity: 14,
          minThreshold: 15,
          statusText: 'Below Min Threshold (15)',
          isWarning: true,
        },
        {
          storeId: 'store-02',
          storeName: 'Northside Galleria #02',
          locationText: 'Display Bay 03',
          quantity: 8,
          minThreshold: 10,
          statusText: 'Below Min Threshold (10)',
          isWarning: true,
        },
      ],
    },
    recentActivity: [
      {
        id: 'act-4',
        title: 'POS Register Sale (1 unit)',
        reference: '#ORD-9820',
        timeAgo: 'Yesterday',
        type: 'sale',
        units: -1,
      },
    ],
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-03-11T16:00:00Z',
  },
  {
    id: 'prod-1027',
    productCode: 'PRD-1027',
    name: 'Garment Alteration & Hemming',
    brand: 'In-Store Tailoring Service',
    categoryId: 'service',
    categoryName: 'Service',
    subcategory: 'Tailoring & Repairs',
    type: 'service',
    sku: 'SRV-ALT-01',
    barcode: undefined,
    hsnCode: '9988.21.00',
    unitOfMeasure: 'Job / Service',
    sellingPrice: 15.0,
    mrp: undefined,
    cost: 5.0,
    minSellingPrice: 15.0,
    discountAllowed: false,
    taxCategory: 'GST 18% (Service Rates)',
    status: 'active',
    reorderLevel: undefined,
    reorderQuantity: undefined,
    openingStock: undefined,
    primarySupplier: 'Internal Master Tailors',
    supplierProductCode: 'INT-SRV-01',
    description:
      'Standard turnaround pants length hemming, sleeve shortening, or waist suppression performed by in-house master tailors within 24-48 hours.',
    imageUrl:
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Tailor working on garment alteration',
    variantsConfigured: 'Type (Trouser Hemming, Waist Suppression, Sleeve Adjustment)',
    stockSummary: undefined, // Service products do not require inventory stock
    recentActivity: [
      {
        id: 'act-5',
        title: 'POS Service Booked (1 ticket)',
        reference: '#ORD-9844',
        timeAgo: '1 hr ago',
        type: 'sale',
        units: 1,
      },
    ],
    createdAt: '2024-01-10T11:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'prod-1028',
    productCode: 'PRD-1028',
    name: 'Organic Indigo Denim Jeans',
    brand: 'Aura Basics',
    categoryId: 'apparel',
    categoryName: 'Apparel / Bottoms',
    subcategory: 'Denim & Trousers',
    type: 'stockable',
    sku: 'AP-JN-305',
    barcode: '8904512304',
    hsnCode: '6203.42.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 62.0,
    mrp: 70.0,
    cost: 28.0,
    minSellingPrice: 55.0,
    discountAllowed: true,
    taxCategory: 'GST 12% (Standard Apparel)',
    status: 'inactive',
    reorderLevel: 20,
    reorderQuantity: 60,
    openingStock: 0,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Global Denim Corp (SUP-204)',
    supplierProductCode: 'GDC-IND-77',
    description:
      '13.5oz ring-spun organic cotton selvedge denim in raw deep indigo wash with copper rivets and button fly construction.',
    imageUrl:
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Folded organic indigo denim jeans',
    variantsConfigured: 'Waist (30, 32, 34, 36), Inseam (30, 32)',
    stockSummary: {
      onHandTotal: 0,
      reorderLevel: 20,
      status: 'OUT_OF_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Denim Wall Section C',
          quantity: 0,
          minThreshold: 10,
          statusText: 'Depleted (PO Required)',
          isWarning: true,
        },
        {
          storeId: 'store-02',
          storeName: 'Northside Galleria #02',
          locationText: 'Depleted',
          quantity: 0,
          minThreshold: 10,
          statusText: 'Depleted (PO Required)',
          isWarning: true,
        },
      ],
    },
    recentActivity: [
      {
        id: 'act-6',
        title: 'Catalog Status Changed',
        reference: 'Archived by Sarah Jenkins',
        timeAgo: '3 days ago',
        type: 'adjustment',
        units: 0,
      },
    ],
    createdAt: '2024-01-20T12:00:00Z',
    updatedAt: '2024-03-08T15:30:00Z',
  },
  {
    id: 'prod-1029',
    productCode: 'PRD-1029',
    name: 'Kraft Carry Bag - Medium',
    brand: 'EcoKraft Packaging',
    categoryId: 'consumables',
    categoryName: 'Consumables',
    subcategory: 'Store Packaging',
    type: 'consumable',
    sku: 'CN-KB-002',
    barcode: '8904512305',
    hsnCode: '4819.20.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 0.5,
    mrp: undefined,
    cost: 0.18,
    minSellingPrice: 0.5,
    discountAllowed: false,
    taxCategory: 'GST 5% (Essential Packaging)',
    status: 'active',
    reorderLevel: 500,
    reorderQuantity: 2000,
    openingStock: 1200,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'EcoKraft Packaging (SUP-105)',
    supplierProductCode: 'EKP-BAG-MED',
    description:
      'Recycled 120gsm virgin kraft paper carrier shopping bags with twisted paper handles. Branded with water-based soy ink.',
    imageUrl:
      'https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Brown recycled kraft shopping carry bag',
    variantsConfigured: 'Size: Medium (26cm x 12cm x 35cm)',
    stockSummary: {
      onHandTotal: 1450,
      reorderLevel: 500,
      status: 'IN_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Checkout Counter Storage Bay',
          quantity: 850,
          minThreshold: 300,
          statusText: 'Safe (Min: 300)',
        },
        {
          storeId: 'store-04',
          storeName: 'Houston Galleria #04',
          locationText: 'Under Cash Registers 1-3',
          quantity: 600,
          minThreshold: 200,
          statusText: 'Safe (Min: 200)',
        },
      ],
    },
    recentActivity: [
      {
        id: 'act-7',
        title: 'Bulk Box Inbound (+1000)',
        reference: 'PO-2024-850',
        timeAgo: '4 days ago',
        type: 'replenishment',
        units: 1000,
      },
    ],
    createdAt: '2024-01-05T09:00:00Z',
    updatedAt: '2024-03-05T14:00:00Z',
  },
  {
    id: 'prod-1030',
    productCode: 'PRD-1030',
    name: 'Handwoven Mulberry Silk Scarf',
    brand: 'Punarva Studio',
    categoryId: 'accessories',
    categoryName: 'Accessories / Scarves',
    subcategory: 'Scarves & Wraps',
    type: 'stockable',
    sku: 'AC-SC-501',
    barcode: '8904512306',
    hsnCode: '6214.10.00',
    unitOfMeasure: 'Pieces (Pcs)',
    sellingPrice: 38.0,
    mrp: 45.0,
    cost: 16.5,
    minSellingPrice: 35.0,
    discountAllowed: true,
    taxCategory: 'GST 12% (Standard Apparel)',
    status: 'active',
    reorderLevel: 15,
    reorderQuantity: 30,
    openingStock: 45,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Aura Organic Mills (SUP-108)',
    supplierProductCode: 'AOM-SLK-12',
    description:
      'Pure artisanal mulberry silk scarf with hand-rolled hems and traditional botanical indigo block print motifs.',
    imageUrl:
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Silk scarf with botanical print',
    variantsConfigured: 'Prints (Indigo Vine, Ochre Bloom)',
    stockSummary: {
      onHandTotal: 34,
      reorderLevel: 15,
      status: 'IN_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Accessory Showcase 01',
          quantity: 20,
          minThreshold: 8,
          statusText: 'Safe (Min: 8)',
        },
        {
          storeId: 'store-03',
          storeName: 'Dallas Uptown #03',
          locationText: 'Silk Island Tower',
          quantity: 14,
          minThreshold: 7,
          statusText: 'Safe (Min: 7)',
        },
      ],
    },
    recentActivity: [],
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-03-02T10:00:00Z',
  },
  {
    id: 'prod-1031',
    productCode: 'PRD-1031',
    name: 'Minimalist Leather Derby Shoes',
    brand: 'Zenith Threads',
    categoryId: 'footwear',
    categoryName: 'Footwear / Shoes',
    subcategory: 'Formal & Casual Footwear',
    type: 'stockable',
    sku: 'FW-DB-401',
    barcode: '8904512307',
    hsnCode: '6403.59.00',
    unitOfMeasure: 'Pairs (Prs)',
    sellingPrice: 110.0,
    mrp: 130.0,
    cost: 49.0,
    minSellingPrice: 95.0,
    discountAllowed: true,
    taxCategory: 'GST 18% (Footwear Above $100)',
    status: 'active',
    reorderLevel: 12,
    reorderQuantity: 24,
    openingStock: 18,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Global Leatherworks (SUP-301)',
    supplierProductCode: 'GLW-DRB-09',
    description:
      'Vegetable-tanned full-grain calfskin leather derby with Blake-stitched leather soles and memory foam insoles.',
    imageUrl:
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Tan leather derby shoes',
    variantsConfigured: 'EU Size (40, 41, 42, 43, 44), Color (Cognac Tan, Espresso)',
    stockSummary: {
      onHandTotal: 10,
      reorderLevel: 12,
      status: 'LOW_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Footwear Wall Unit 2',
          quantity: 6,
          minThreshold: 6,
          statusText: 'At Min Threshold',
          isWarning: true,
        },
        {
          storeId: 'store-02',
          storeName: 'Northside Galleria #02',
          locationText: 'Shoe Display Rack',
          quantity: 4,
          minThreshold: 6,
          statusText: 'Below Threshold (6)',
          isWarning: true,
        },
      ],
    },
    recentActivity: [],
    createdAt: '2024-02-14T11:20:00Z',
    updatedAt: '2024-03-10T12:10:00Z',
  },
  {
    id: 'prod-1032',
    productCode: 'PRD-1032',
    name: 'Handloom Cotton Fabric (Per Metre)',
    brand: 'Punarva Studio',
    categoryId: 'fabrics',
    categoryName: 'Fabrics',
    subcategory: 'Raw Textiles',
    type: 'stockable',
    sku: 'FB-CT-108',
    barcode: '8904512308',
    hsnCode: '5208.11.00',
    unitOfMeasure: 'Meter (Mtr)',
    sellingPrice: 8.5,
    mrp: 10.0,
    cost: 3.8,
    minSellingPrice: 7.5,
    discountAllowed: true,
    taxCategory: 'GST 5% (Textile Fabrics)',
    status: 'active',
    reorderLevel: 80,
    reorderQuantity: 200,
    openingStock: 150,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Aura Organic Mills (SUP-108)',
    supplierProductCode: 'AOM-HL-60',
    description:
      '60s count breathable handspun unbleached organic cotton running fabric, ideal for bespoke shirts and soft drapery.',
    imageUrl:
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Natural handloom cotton fabric rolls',
    variantsConfigured: 'Width: 44 inches • Natural Unbleached',
    stockSummary: {
      onHandTotal: 185,
      reorderLevel: 80,
      status: 'IN_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Textile Spindle Rack A',
          quantity: 185,
          minThreshold: 80,
          statusText: 'Safe (Min: 80)',
        },
      ],
    },
    recentActivity: [],
    createdAt: '2024-01-28T14:00:00Z',
    updatedAt: '2024-03-04T16:00:00Z',
  },
  {
    id: 'prod-1033',
    productCode: 'PRD-1033',
    name: 'Aromatic Cedar Shoe Trees (Pair)',
    brand: 'Zenith Lifestyle',
    categoryId: 'lifestyle',
    categoryName: 'Lifestyle',
    subcategory: 'Shoe Care & Accents',
    type: 'stockable',
    sku: 'LF-ST-044',
    barcode: '8904512309',
    hsnCode: '4421.99.00',
    unitOfMeasure: 'Pairs (Prs)',
    sellingPrice: 28.0,
    mrp: 35.0,
    cost: 12.0,
    minSellingPrice: 24.0,
    discountAllowed: true,
    taxCategory: 'GST 18% (Lifestyle Accents)',
    status: 'inactive',
    reorderLevel: 20,
    reorderQuantity: 40,
    openingStock: 0,
    openingStoreOutlet: 'Downtown Flagship #01',
    primarySupplier: 'Zenith Lifestyle Goods',
    supplierProductCode: 'ZLG-CDR-01',
    description:
      'Natural Eastern red cedar shoe trees with spring-loaded brass tube and sculpted heel contour to absorb moisture and preserve shoe shape.',
    imageUrl:
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400&auto=format&fit=crop&q=80',
    imageAlt: 'Pair of aromatic cedar shoe trees',
    variantsConfigured: 'Size: S (39-40), M (41-42), L (43-44)',
    stockSummary: {
      onHandTotal: 0,
      reorderLevel: 20,
      status: 'OUT_OF_STOCK',
      storeBreakdown: [
        {
          storeId: 'store-01',
          storeName: 'Downtown Flagship #01',
          locationText: 'Shoe Care Display Cabinet',
          quantity: 0,
          minThreshold: 10,
          statusText: 'Out of Stock',
          isWarning: true,
        },
      ],
    },
    recentActivity: [],
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-02-28T17:00:00Z',
  },
];

export const CATEGORIES = [
  'All Categories',
  'Apparel',
  'Footwear',
  'Accessories',
  'Lifestyle',
  'Fabrics',
  'Consumables',
  'Service',
];

export const BRANDS = [
  'All Brands',
  'Punarva Studio',
  'Aura Basics',
  'EcoKraft Packaging',
  'Zenith Lifestyle',
  'Zenith Threads',
  'In-Store Tailoring Service',
];
