import { Purchase } from '../types';

export interface SupplierOption {
  id: string;
  name: string;
  taxId?: string;
  note?: string;
  contact?: string;
}

export interface OutletOption {
  id: string;
  name: string;
  isOrgWide?: boolean;
}

export const MOCK_SUPPLIERS: SupplierOption[] = [
  {
    id: 'sup-101',
    name: 'Zenith Textile Mills',
    taxId: 'US-8829104',
    note: 'Preferred fabric & apparel vendor',
    contact: 'orders@zenithtextile.com',
  },
  {
    id: 'sup-102',
    name: 'Apex Global Electronics',
    contact: 'rep: john@apexge.com',
    note: 'Barcode scanners & retail hardware',
  },
  {
    id: 'sup-103',
    name: 'EcoKraft Packaging Ltd.',
    note: 'Net 30 Terms',
    contact: 'billing@ecokraft.net',
  },
  {
    id: 'sup-104',
    name: 'Cascade Beverage Co.',
    note: 'Direct DSD Route',
    contact: 'rep@cascadebev.com',
  },
  {
    id: 'sup-105',
    name: 'Horizon Hardware Direct',
    note: 'Quote Pending',
    contact: 'wholesale@horizonhw.com',
  },
  {
    id: 'sup-106',
    name: 'Metro Office Logistics',
    note: 'Discontinued supplier',
    contact: 'support@metrooffice.org',
  },
  {
    id: 'sup-107',
    name: 'Vanguard Leather Goods',
    note: 'Net 15 Terms',
    contact: 'orders@vanguardleather.com',
  },
  {
    id: 'sup-108',
    name: 'Lumina Store Displays',
    taxId: 'US-9912041',
    note: 'Direct Fixtures & Bags',
    contact: 'sales@luminadisplays.com',
  },
];

export const MOCK_OUTLETS: OutletOption[] = [
  { id: 'outlet-04', name: 'Downtown Flagship #04', isOrgWide: false },
  { id: 'outlet-12', name: 'Uptown Mall #12', isOrgWide: false },
  { id: 'outlet-08', name: 'Westside Express #08', isOrgWide: false },
  { id: 'outlet-03', name: 'Houston Galleria #03', isOrgWide: false },
  { id: 'outlet-org', name: 'Organization-wide', isOrgWide: true },
];

export const INITIAL_PURCHASES: Purchase[] = [
  // Row 1: PUR-2024-104 (Approved Stitch Hero Row)
  {
    id: 'pur-104',
    purchaseNumber: 'PUR-2024-104',
    purchaseOrderNumber: 'PO-2024-082',
    invoiceNumber: 'INV-ZTM-8821',
    date: 'Oct 24, 2024',
    time: '10:15 AM',
    timestamp: new Date('2024-10-24T10:15:00').getTime(),
    supplierId: 'sup-101',
    supplierName: 'Zenith Textile Mills',
    supplierTaxId: 'tax-id: US-8829104',
    supplierContact: 'orders@zenithtextile.com',
    supplierNote: 'Preferred Apparel Mill',
    outletId: 'outlet-04',
    outletName: 'Downtown Flagship #04',
    scope: 'outlet',
    items: [
      {
        id: 'item-104-1',
        productId: 'prod-1024',
        productCode: 'PRD-1024',
        productName: 'Classic Linen Relaxed Shirt',
        sku: 'AP-SH-001',
        variantInfo: 'PRD-1024 · Sand / L',
        quantityOrdered: 50,
        quantityReceived: 35,
        unitCost: 22.5,
        discountPercent: 0,
        taxRate: 12,
        taxAmount: 135.0,
        lineTotal: 1260.0,
      },
      {
        id: 'item-104-2',
        productId: 'prod-1026',
        productCode: 'PRD-1026',
        productName: 'Tailored Wool Blazer',
        sku: 'AP-JK-003',
        variantInfo: 'PRD-1026 · Charcoal / 40R',
        quantityOrdered: 25,
        quantityReceived: 25,
        unitCost: 65.0,
        discountPercent: 0,
        taxRate: 12,
        taxAmount: 195.0,
        lineTotal: 1820.0,
      },
      {
        id: 'item-104-3',
        productId: 'prod-1029',
        productCode: 'PRD-1029',
        productName: 'Kraft Carry Bags (100-pack)',
        sku: 'PKG-BG-100',
        variantInfo: 'PRD-1029 · Medium Logo',
        quantityOrdered: 20,
        quantityReceived: 0,
        unitCost: 15.0,
        discountPercent: 0,
        taxRate: 18,
        taxAmount: 54.0,
        lineTotal: 354.0,
      },
    ],
    totalUnits: 95,
    subtotal: 2980.0,
    shippingFee: 120.0,
    handlingFee: 0.0,
    tax: 340.0,
    totalAmount: 3420.0,
    amountPaid: 1500.0,
    outstandingAmount: 1920.0,
    paymentStatus: 'PARTIALLY_PAID',
    receiptStatus: 'PARTIALLY_RECEIVED',
    status: 'active',
    paymentMethodNote: 'Tax Incl.',
    paidNote: '$1,500 Paid',
    dueDate: '2024-11-08',
    paymentTerms: 'Net 15 Days',
    receivingNotes: 'Store Stockroom Bay B',
    batchNumber: 'BATCH-2024-OCT-09',
    mfgDate: '2024-10-01',
    expiryDate: '2027-10-01',
    createdBy: 'Sarah Jenkins',
    creatorRole: 'Store Mgr',
    attachments: [
      {
        id: 'att-104-1',
        name: 'INV-ZTM-8821_Signed_Challan.pdf',
        size: '1.8 MB',
        uploader: 'Sarah Jenkins',
        date: 'Oct 24 10:20 AM',
        fileType: 'pdf',
      },
    ],
    auditTrail: [
      {
        id: 'aud-1',
        title: 'Partial stock receipt (35 units) logged',
        timeAgo: 'Today, Oct 24, 10:15 AM',
        details: 'Inventory Specialist David Chen verified physical items at Flagship dock #2.',
        timestamp: '2024-10-24T10:15:00',
        dotType: 'primary',
      },
      {
        id: 'aud-2',
        title: 'Partial payment of $1,500.00 posted via Bank Wire',
        timeAgo: 'Oct 23, 03:00 PM',
        details: 'Transaction Ref: WIRE-99812903. Handled by Marcus Vance.',
        timestamp: '2024-10-23T15:00:00',
        dotType: 'outline',
      },
      {
        id: 'aud-3',
        title: 'Purchase Order PO-2024-082 created and dispatched',
        timeAgo: 'Oct 22, 11:45 AM',
        details: 'Created by Sarah Jenkins (STORE MGR). Approved automatically.',
        timestamp: '2024-10-22T11:45:00',
        dotType: 'variant',
      },
    ],
    createdAt: '2024-10-22T11:45:00Z',
    updatedAt: '2024-10-24T10:15:00Z',
  },

  // Row 2: PUR-2024-103
  {
    id: 'pur-103',
    purchaseNumber: 'PUR-2024-103',
    purchaseOrderNumber: 'PO-2024-079',
    invoiceNumber: 'INV-APX-7740',
    date: 'Oct 22, 2024',
    time: '02:40 PM',
    timestamp: new Date('2024-10-22T14:40:00').getTime(),
    supplierId: 'sup-102',
    supplierName: 'Apex Global Electronics',
    supplierContact: 'rep: john@apexge.com',
    outletId: 'outlet-12',
    outletName: 'Uptown Mall #12',
    scope: 'outlet',
    items: [
      {
        id: 'item-103-1',
        productId: 'prod-pos-term',
        productCode: 'HW-POS-01',
        productName: 'Enterprise Wireless Barcode Terminal',
        sku: 'HW-BC-200',
        quantityOrdered: 20,
        quantityReceived: 20,
        unitCost: 450.0,
        discountPercent: 0,
        taxRate: 18,
        taxAmount: 1620.0,
        lineTotal: 10620.0,
      },
      {
        id: 'item-103-2',
        productId: 'prod-rec-prn',
        productCode: 'HW-PRN-02',
        productName: 'Thermal Direct Receipt Printers',
        sku: 'HW-TH-100',
        quantityOrdered: 10,
        quantityReceived: 10,
        unitCost: 170.0,
        discountPercent: 0,
        taxRate: 16,
        taxAmount: 280.0,
        lineTotal: 1980.0,
      },
    ],
    totalUnits: 30,
    subtotal: 10700.0,
    shippingFee: 0.0,
    handlingFee: 0.0,
    tax: 1900.0,
    totalAmount: 12600.0,
    amountPaid: 12600.0,
    outstandingAmount: 0.0,
    paymentStatus: 'PAID',
    receiptStatus: 'RECEIVED',
    status: 'active',
    paymentMethodNote: 'Fully Settled',
    paymentTerms: 'Immediate / Cash',
    createdBy: 'Marcus Vance',
    creatorRole: 'Procurement Head',
    createdAt: '2024-10-20T09:00:00Z',
    updatedAt: '2024-10-22T14:40:00Z',
  },

  // Row 3: PUR-2024-102
  {
    id: 'pur-102',
    purchaseNumber: 'PUR-2024-102',
    purchaseOrderNumber: 'PO-2024-075',
    invoiceNumber: 'INV-EKP-9021',
    date: 'Oct 20, 2024',
    time: '09:05 AM',
    timestamp: new Date('2024-10-20T09:05:00').getTime(),
    supplierId: 'sup-103',
    supplierName: 'EcoKraft Packaging Ltd.',
    supplierNote: 'Net 30 Terms',
    supplierContact: 'billing@ecokraft.net',
    outletId: 'outlet-org',
    outletName: 'Organization-wide',
    scope: 'organization',
    items: [
      {
        id: 'item-102-1',
        productId: 'prod-1029',
        productCode: 'PRD-1029',
        productName: 'Eco Kraft Carrier Sacks (500)',
        sku: 'PKG-BG-500',
        quantityOrdered: 500,
        quantityReceived: 500,
        unitCost: 3.35,
        discountPercent: 0,
        taxRate: 10,
        taxAmount: 175.0,
        lineTotal: 1850.0,
      },
    ],
    totalUnits: 500,
    subtotal: 1675.0,
    shippingFee: 0.0,
    handlingFee: 0.0,
    tax: 175.0,
    totalAmount: 1850.0,
    amountPaid: 0.0,
    outstandingAmount: 1850.0,
    paymentStatus: 'UNPAID',
    receiptStatus: 'RECEIVED',
    status: 'active',
    paymentMethodNote: 'Due in 10 days',
    dueDate: '2024-10-30',
    paymentTerms: 'Net 30 Terms',
    createdBy: 'Sarah Jenkins',
    creatorRole: 'Store Mgr',
    createdAt: '2024-10-18T11:00:00Z',
    updatedAt: '2024-10-20T09:05:00Z',
  },

  // Row 4: PUR-2024-101
  {
    id: 'pur-101',
    purchaseNumber: 'PUR-2024-101',
    purchaseOrderNumber: 'PO-2024-071',
    invoiceNumber: 'INV-CSB-4412',
    date: 'Oct 18, 2024',
    time: '11:30 AM',
    timestamp: new Date('2024-10-18T11:30:00').getTime(),
    supplierId: 'sup-104',
    supplierName: 'Cascade Beverage Co.',
    supplierNote: 'Direct DSD Route',
    outletId: 'outlet-08',
    outletName: 'Westside Express #08',
    scope: 'outlet',
    items: [
      {
        id: 'item-101-1',
        productId: 'prod-bev-01',
        productCode: 'PRD-3301',
        productName: 'Sparkling Spring Water (24pk)',
        sku: 'BEV-SP-024',
        quantityOrdered: 80,
        quantityReceived: 80,
        unitCost: 12.0,
        discountPercent: 0,
        taxRate: 5,
        taxAmount: 48.0,
        lineTotal: 1008.0,
      },
      {
        id: 'item-101-2',
        productId: 'prod-bev-02',
        productCode: 'PRD-3302',
        productName: 'Cold Brew Craft Tea (12pk)',
        sku: 'BEV-TEA-012',
        quantityOrdered: 80,
        quantityReceived: 80,
        unitCost: 13.0,
        discountPercent: 0,
        taxRate: 5,
        taxAmount: 52.0,
        lineTotal: 1132.0,
      },
    ],
    totalUnits: 160,
    subtotal: 2000.0,
    shippingFee: 40.0,
    handlingFee: 0.0,
    tax: 100.0,
    totalAmount: 2140.0,
    amountPaid: 2140.0,
    outstandingAmount: 0.0,
    paymentStatus: 'PAID',
    receiptStatus: 'RECEIVED',
    status: 'active',
    paymentMethodNote: 'Paid via ACH',
    paymentTerms: 'Immediate / Cash',
    createdBy: 'David Chen',
    creatorRole: 'Inventory Lead',
    createdAt: '2024-10-17T08:20:00Z',
    updatedAt: '2024-10-18T11:30:00Z',
  },

  // Row 5: PUR-2024-100
  {
    id: 'pur-100',
    purchaseNumber: 'PUR-2024-100',
    purchaseOrderNumber: 'DRAFT-ORD',
    date: 'Oct 16, 2024',
    time: '04:15 PM',
    timestamp: new Date('2024-10-16T16:15:00').getTime(),
    supplierId: 'sup-105',
    supplierName: 'Horizon Hardware Direct',
    supplierNote: 'Quote Pending',
    outletId: 'outlet-04',
    outletName: 'Downtown Flagship #04',
    scope: 'outlet',
    items: [
      {
        id: 'item-100-1',
        productId: 'prod-hw-hang',
        productCode: 'PRD-4010',
        productName: 'Heavy Chrome Garment Hangers (Box 100)',
        sku: 'ACC-HNG-100',
        quantityOrdered: 15,
        quantityReceived: 0,
        unitCost: 55.0,
        discountPercent: 0,
        taxRate: 8,
        taxAmount: 65.0,
        lineTotal: 890.0,
      },
    ],
    totalUnits: 15,
    subtotal: 825.0,
    shippingFee: 0.0,
    handlingFee: 0.0,
    tax: 65.0,
    totalAmount: 890.0,
    amountPaid: 0.0,
    outstandingAmount: 890.0,
    paymentStatus: 'UNPAID',
    receiptStatus: 'PENDING',
    status: 'draft',
    paymentMethodNote: 'Draft Est.',
    paymentTerms: 'Net 30 Days',
    createdBy: 'Sarah Jenkins',
    creatorRole: 'Store Mgr',
    createdAt: '2024-10-16T16:15:00Z',
    updatedAt: '2024-10-16T16:15:00Z',
  },

  // Row 6: PUR-2024-099 (Voided / Cancelled)
  {
    id: 'pur-099',
    purchaseNumber: 'PUR-2024-099',
    purchaseOrderNumber: 'PO-2024-068',
    invoiceNumber: 'INV-MOL-1102-VOID',
    date: 'Oct 14, 2024',
    time: '10:00 AM',
    timestamp: new Date('2024-10-14T10:00:00').getTime(),
    supplierId: 'sup-106',
    supplierName: 'Metro Office Logistics',
    supplierNote: 'Discontinued supplier',
    outletId: 'outlet-03',
    outletName: 'Houston Galleria #03',
    scope: 'outlet',
    items: [
      {
        id: 'item-099-1',
        productId: 'prod-off-01',
        productCode: 'PRD-5501',
        productName: 'Thermal Register Rolls (Case 50)',
        sku: 'OFF-PPR-050',
        quantityOrdered: 40,
        quantityReceived: 0,
        unitCost: 16.5,
        discountPercent: 0,
        taxRate: 9,
        taxAmount: 60.0,
        lineTotal: 720.0,
      },
    ],
    totalUnits: 40,
    subtotal: 660.0,
    shippingFee: 0.0,
    handlingFee: 0.0,
    tax: 60.0,
    totalAmount: 720.0,
    amountPaid: 0.0,
    outstandingAmount: 0.0,
    paymentStatus: 'UNPAID',
    receiptStatus: 'PENDING',
    status: 'cancelled',
    paymentMethodNote: 'Voided',
    paymentTerms: 'Immediate / Cash',
    createdBy: 'Elena Lin',
    creatorRole: 'Admin',
    createdAt: '2024-10-14T10:00:00Z',
    updatedAt: '2024-10-14T11:20:00Z',
  },

  // Row 7: PUR-2024-098
  {
    id: 'pur-098',
    purchaseNumber: 'PUR-2024-098',
    purchaseOrderNumber: 'PO-2024-065',
    invoiceNumber: 'INV-VLG-8811',
    date: 'Oct 12, 2024',
    time: '03:15 PM',
    timestamp: new Date('2024-10-12T15:15:00').getTime(),
    supplierId: 'sup-107',
    supplierName: 'Vanguard Leather Goods',
    supplierNote: 'Net 15 Terms',
    outletId: 'outlet-04',
    outletName: 'Downtown Flagship #04',
    scope: 'outlet',
    items: [
      {
        id: 'item-098-1',
        productId: 'prod-1027',
        productCode: 'PRD-1027',
        productName: 'Full Grain Leather Card Wallet',
        sku: 'ACC-WL-004',
        quantityOrdered: 60,
        quantityReceived: 60,
        unitCost: 16.0,
        discountPercent: 0,
        taxRate: 12,
        taxAmount: 115.2,
        lineTotal: 1075.2,
      },
    ],
    totalUnits: 60,
    subtotal: 960.0,
    shippingFee: 45.0,
    handlingFee: 0.0,
    tax: 115.2,
    totalAmount: 1120.2,
    amountPaid: 1120.2,
    outstandingAmount: 0.0,
    paymentStatus: 'PAID',
    receiptStatus: 'RECEIVED',
    status: 'active',
    paymentMethodNote: 'Paid via Corporate Card',
    paymentTerms: 'Net 15 Days',
    createdBy: 'Sarah Jenkins',
    creatorRole: 'Store Mgr',
    createdAt: '2024-10-11T14:00:00Z',
    updatedAt: '2024-10-12T15:15:00Z',
  },

  // Row 8: PUR-2024-097
  {
    id: 'pur-097',
    purchaseNumber: 'PUR-2024-097',
    purchaseOrderNumber: 'PO-2024-062',
    invoiceNumber: 'INV-ZTM-8750',
    date: 'Oct 10, 2024',
    time: '11:00 AM',
    timestamp: new Date('2024-10-10T11:00:00').getTime(),
    supplierId: 'sup-101',
    supplierName: 'Zenith Textile Mills',
    supplierTaxId: 'tax-id: US-8829104',
    outletId: 'outlet-12',
    outletName: 'Uptown Mall #12',
    scope: 'outlet',
    items: [
      {
        id: 'item-097-1',
        productId: 'prod-1025',
        productCode: 'PRD-1025',
        productName: 'Selvedge Denim Regular Trousers',
        sku: 'AP-DN-002',
        quantityOrdered: 80,
        quantityReceived: 40,
        unitCost: 32.0,
        discountPercent: 0,
        taxRate: 12,
        taxAmount: 307.2,
        lineTotal: 2867.2,
      },
    ],
    totalUnits: 80,
    subtotal: 2560.0,
    shippingFee: 80.0,
    handlingFee: 0.0,
    tax: 307.2,
    totalAmount: 2947.2,
    amountPaid: 1500.0,
    outstandingAmount: 1447.2,
    paymentStatus: 'PARTIALLY_PAID',
    receiptStatus: 'PARTIALLY_RECEIVED',
    status: 'active',
    paymentMethodNote: 'Due in 5 days',
    paidNote: '$1,500 Paid',
    paymentTerms: 'Net 30 Days',
    createdBy: 'Marcus Vance',
    creatorRole: 'Procurement Head',
    createdAt: '2024-10-09T10:00:00Z',
    updatedAt: '2024-10-10T11:00:00Z',
  },

  // Row 9: PUR-2024-096
  {
    id: 'pur-096',
    purchaseNumber: 'PUR-2024-096',
    purchaseOrderNumber: 'PO-2024-059',
    invoiceNumber: 'INV-LUM-3301',
    date: 'Oct 08, 2024',
    time: '01:25 PM',
    timestamp: new Date('2024-10-08T13:25:00').getTime(),
    supplierId: 'sup-108',
    supplierName: 'Lumina Store Displays',
    outletId: 'outlet-08',
    outletName: 'Westside Express #08',
    scope: 'outlet',
    items: [
      {
        id: 'item-096-1',
        productId: 'prod-fix-01',
        productCode: 'PRD-6101',
        productName: 'Modular Acrylic Tabletop Riser',
        sku: 'DSP-RS-002',
        quantityOrdered: 30,
        quantityReceived: 0,
        unitCost: 40.0,
        discountPercent: 0,
        taxRate: 10,
        taxAmount: 120.0,
        lineTotal: 1320.0,
      },
    ],
    totalUnits: 30,
    subtotal: 1200.0,
    shippingFee: 60.0,
    handlingFee: 0.0,
    tax: 120.0,
    totalAmount: 1380.0,
    amountPaid: 0.0,
    outstandingAmount: 1380.0,
    paymentStatus: 'UNPAID',
    receiptStatus: 'PENDING',
    status: 'active',
    paymentMethodNote: 'Due in 15 days',
    paymentTerms: 'Net 30 Days',
    createdBy: 'David Chen',
    creatorRole: 'Inventory Lead',
    createdAt: '2024-10-07T09:00:00Z',
    updatedAt: '2024-10-08T13:25:00Z',
  },

  // Row 10: PUR-2024-095
  {
    id: 'pur-095',
    purchaseNumber: 'PUR-2024-095',
    purchaseOrderNumber: 'PO-2024-055',
    invoiceNumber: 'INV-APX-7601',
    date: 'Oct 05, 2024',
    time: '09:40 AM',
    timestamp: new Date('2024-10-05T09:40:00').getTime(),
    supplierId: 'sup-102',
    supplierName: 'Apex Global Electronics',
    outletId: 'outlet-04',
    outletName: 'Downtown Flagship #04',
    scope: 'outlet',
    items: [
      {
        id: 'item-095-1',
        productId: 'prod-pos-cables',
        productCode: 'HW-CBL-09',
        productName: 'High-Speed USB-C POS Terminal Interface Cables',
        sku: 'CBL-UC-100',
        quantityOrdered: 50,
        quantityReceived: 50,
        unitCost: 8.5,
        discountPercent: 0,
        taxRate: 15,
        taxAmount: 63.75,
        lineTotal: 488.75,
      },
    ],
    totalUnits: 50,
    subtotal: 425.0,
    shippingFee: 20.0,
    handlingFee: 0.0,
    tax: 63.75,
    totalAmount: 508.75,
    amountPaid: 508.75,
    outstandingAmount: 0.0,
    paymentStatus: 'PAID',
    receiptStatus: 'RECEIVED',
    status: 'active',
    paymentMethodNote: 'Fully Settled',
    paymentTerms: 'Immediate / Cash',
    createdBy: 'Sarah Jenkins',
    creatorRole: 'Store Mgr',
    createdAt: '2024-10-04T16:00:00Z',
    updatedAt: '2024-10-05T09:40:00Z',
  },

  // Additional realistic purchases bringing active total to 42 items
  // Sept & Aug purchases, and earlier Oct purchases
  ...Array.from({ length: 32 }, (_, idx) => {
    const pNum = 94 - idx;
    const isCancelled = idx === 12; // One other cancelled in past
    const isSept = idx >= 10;
    const day = isSept ? Math.max(1, 28 - (idx - 10)) : Math.max(1, 5 - Math.floor(idx / 3));
    const monthStr = isSept ? 'Sep' : 'Oct';
    const year = 2024;
    const supp = MOCK_SUPPLIERS[idx % MOCK_SUPPLIERS.length];
    const outlet = MOCK_OUTLETS[idx % MOCK_OUTLETS.length];
    const isPaid = idx % 3 === 0;
    const isPartial = idx % 3 === 1;
    const isPendingRecv = idx % 4 === 1;

    const qty1 = 20 + (idx % 5) * 10;
    const cost1 = 15.0 + (idx % 7) * 4.5;
    const lineSub = qty1 * cost1;
    const taxAmt = lineSub * 0.12;
    const total = Number((lineSub + taxAmt + 50).toFixed(2));
    const paid = isPaid ? total : isPartial ? Number((total * 0.5).toFixed(2)) : 0;
    const out = Number((total - paid).toFixed(2));

    return {
      id: `pur-${pNum}`,
      purchaseNumber: `PUR-2024-0${pNum < 10 ? '0' + pNum : pNum}`,
      purchaseOrderNumber: `PO-2024-0${pNum - 20}`,
      invoiceNumber: `INV-${supp.name.slice(0, 3).toUpperCase()}-${pNum * 31}`,
      date: `${monthStr} ${day < 10 ? '0' + day : day}, ${year}`,
      time: `${10 + (idx % 6)}:${idx % 2 === 0 ? '15' : '45'} AM`,
      timestamp: new Date(`${year}-${isSept ? '09' : '10'}-${day < 10 ? '0' + day : day}T10:00:00`).getTime(),
      supplierId: supp.id,
      supplierName: supp.name,
      supplierTaxId: supp.taxId ? `tax-id: ${supp.taxId}` : undefined,
      supplierContact: supp.contact,
      supplierNote: supp.note,
      outletId: outlet.id,
      outletName: outlet.name,
      scope: outlet.isOrgWide ? 'organization' : 'outlet',
      items: [
        {
          id: `item-${pNum}-1`,
          productId: `prod-var-${idx}`,
          productCode: `PRD-${2000 + idx}`,
          productName: `Assorted Inventory Restock Lot #${idx + 1}`,
          sku: `SKU-RESTOCK-${idx + 10}`,
          quantityOrdered: qty1,
          quantityReceived: isPendingRecv ? 0 : qty1,
          unitCost: cost1,
          discountPercent: 0,
          taxRate: 12,
          taxAmount: Number(taxAmt.toFixed(2)),
          lineTotal: total,
        },
      ],
      totalUnits: qty1,
      subtotal: Number(lineSub.toFixed(2)),
      shippingFee: 50.0,
      handlingFee: 0.0,
      tax: Number(taxAmt.toFixed(2)),
      totalAmount: total,
      amountPaid: isCancelled ? 0 : paid,
      outstandingAmount: isCancelled ? 0 : out,
      paymentStatus: isPaid ? 'PAID' : isPartial ? 'PARTIALLY_PAID' : 'UNPAID',
      receiptStatus: isPendingRecv ? 'PENDING' : 'RECEIVED',
      status: isCancelled ? 'cancelled' : 'active',
      paymentMethodNote: isPaid ? 'Paid via ACH' : isPartial ? 'Net 30 Terms' : 'Due in 20 days',
      paidNote: isPartial ? `$${paid.toLocaleString()} Paid` : undefined,
      paymentTerms: 'Net 30 Days',
      createdBy: idx % 2 === 0 ? 'Sarah Jenkins' : 'David Chen',
      creatorRole: idx % 2 === 0 ? 'Store Mgr' : 'Inventory Lead',
      createdAt: `${year}-${isSept ? '09' : '10'}-${day < 10 ? '0' + day : day}T08:00:00Z`,
      updatedAt: `${year}-${isSept ? '09' : '10'}-${day < 10 ? '0' + day : day}T10:00:00Z`,
    } as Purchase;
  }),
];
